# Generated by Django 4.2.1 on 2023-08-01 17:58

from django.db import migrations, models
import frontendapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date_field', models.DateField(validators=[frontendapp.models.validate_future_date])),
                ('choose_doctor', models.CharField(max_length=100)),
                ('choose_department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[frontendapp.models.validate_phone_number])),
                ('email_id', models.EmailField(max_length=254)),
                ('time_slot', models.TimeField()),
            ],
        ),
    ]
