# Generated by Django 4.2.1 on 2023-08-01 18:36

from django.db import migrations, models
import frontendapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[frontendapp.models.validate_phone_number]),
        ),
    ]
