# Generated by Django 4.2.1 on 2023-08-02 04:24

from django.db import migrations, models
import frontendapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0002_alter_mymodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[frontendapp.models.validate_phone_number]),
        ),
    ]
